### ISSUE TITLE
I´m a begginer so I don´t get it

### ISSUE THREAD

**Issue by findasolution** [ChristianPerez34/AutoCryptoClaimer#19]
Traceback (most recent call last):
  File "C:\Users\A-10\Desktop\BTO\FaucetCollector\NEW TRY\AutoCryptoClaimer\app.py", line 7, in <module>
    from faucet_collector.crypto_claimer import CryptoClaimer
  File "C:\Users\A-10\Desktop\BTO\FaucetCollector\NEW TRY\AutoCryptoClaimer\faucet_collector\crypto_claimer.py", line 3, in <module>
    from msedge.selenium_tools import Edge
ModuleNotFoundError: No module named 'msedge'

**Comment by ChristianPerez34** [comment]
Hi!

Please install the following python package

msedge-selenium-tools = "^3.141.3"

**Comment by findasolution** [comment]
Thanks
